package code.exampleshop.domain.common;

public enum ErrorCode {
    ORDER_ALREADY_CANCELLED,
    ORDER_ALREADY_SHIPPED,
    ORDER_CANNOT_CANCEL_AFTER_PAYMENT_APPROVED,
    PAYMENT_NOT_READY,
    PAYMENT_ALREADY_APPROVED,
    PAYMENT_ALREADY_FAILED,
    INVALID_PAYMENT_AMOUNT,
    ORDER_TOTAL_PRICE_MISMATCH,
    ORDER_NOT_FOUND,
    PAYMENT_NOT_FOUND
}